name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # =========================
    # RESTORE
    # =========================

    - name: Restore API
      run: dotnet restore ./src/ChessAIWebAPI/ChessAIWebAPI.sln

    - name: Restore WPF
      run: dotnet restore ./src/ChessAIApp/ChessAIApp.sln

    - name: Restore Tests
      run: dotnet restore ./tests/ChessAIApp.Tests/ChessAIApp.Tests.csproj

    # =========================
    # BUILD
    # =========================

    - name: Build API
      run: dotnet build ./src/ChessAIWebAPI/ChessAIWebAPI.sln --configuration Release --no-restore

    - name: Build WPF
      run: dotnet build ./src/ChessAIApp/ChessAIApp.sln --configuration Release --no-restore

    - name: Build Tests
      run: dotnet build ./tests/ChessAIApp.Tests/ChessAIApp.Tests.csproj --configuration Release --no-restore

    # =========================
    # TESTS
    # =========================

    - name: Run Tests
      run: dotnet test ./tests/ChessAIApp.Tests/ChessAIApp.Tests.csproj --configuration Release --no-build --logger "trx"

    # =========================
    # PUBLISH
    # =========================

    - name: Publish API
      run: dotnet publish ./src/ChessAIWebAPI -c Release -o publish/api

    - name: Publish WPF
      run: dotnet publish ./src/ChessAIApp -c Release -o publish/wpf

    # =========================
    # ARTIFACTS
    # =========================

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: publish/